logging:
  level:
    com.ringochi.notificationservice: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:15441/notification_db
    username: notification_service
    password: notification_service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
