server:
  port: 8083

spring:
  application:
    name: route-service
  config:
    import: optional:configserver:http://localhost:8889
  datasource:
    url: jdbc:postgresql://localhost:15434/route_db
    username: route_service
    password: route_service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
