server:
  port: 8084

spring:
  application:
    name: trip-service
  config:
    import: optional:configserver:http://localhost:8889
  datasource:
    url: jdbc:postgresql://localhost:15435/trip_db
    username: trip_service
    password: trip_service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
