server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8889
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: route-cities
          uri: lb://route-service
          predicates:
            - Path=/api/cities/**
        - id: route-service
          uri: lb://route-service
          predicates:
            - Path=/api/routes/**
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/drivers/**
        - id: cargo-service
          uri: lb://cargo-service
          predicates:
            - Path=/api/cargo-orders/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: "system-transport-demo-secret-must-be-at-least-32-bytes"
