server:
  port: 8085

spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:http://localhost:8889
  datasource:
    url: jdbc:postgresql://localhost:15436/booking_db
    username: booking_service
    password: booking_service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ringochi.bookingservice.PaymentEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
